name: Build Docker and Push

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  docker-build-for-api:
    name: Docker Build and Push for API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: files
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: jitterbit/get-changed-files@v1
      - name: Check if files changed
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ ${changed_file} =~ ^openg2p-g2p-bridge-models || \
                  ${changed_file} =~ ^openg2p-g2p-bridge-api || \
                  ${changed_file} == Dockerfile.api || \
                  ${changed_file} == *.dockerignore ]]
            then
              echo DOCKER_BUILD=true >> $GITHUB_ENV
              break
            fi
          done
      - name: Docker build and push
        uses: ./.github/actions/docker-build
        if: ${{ github.event_name == 'workflow_dispatch' || env.DOCKER_BUILD == 'true' }}
        with:
          NAMESPACE: ${{ secrets.docker_hub_organisation || 'openg2p' }}
          SERVICE_NAME: openg2p-g2p-bridge-api
          DOCKERFILE_PATH: Dockerfile.api
          DOCKER_HUB_TOKEN: ${{ secrets.docker_hub_token }}
          DOCKER_HUB_ACTOR: ${{ secrets.docker_hub_actor }}

  docker-build-for-producer:
    name: Docker Build and Push for Celery Beat Producer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: files
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: jitterbit/get-changed-files@v1
      - name: Check if files changed
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ ${changed_file} =~ ^openg2p-g2p-bridge-models || \
                  ${changed_file} =~ ^openg2p-g2p-bridge-bank-connectors || \
                  ${changed_file} =~ ^openg2p-g2p-bridge-celery-beat-producers || \
                  ${changed_file} == Dockerfile.producers || \
                  ${changed_file} == *.dockerignore ]]
            then
              echo DOCKER_BUILD=true >> $GITHUB_ENV
              break
            fi
          done
      - name: Docker build and push
        uses: ./.github/actions/docker-build
        if: ${{ github.event_name == 'workflow_dispatch' || env.DOCKER_BUILD == 'true' }}
        with:
          NAMESPACE: ${{ secrets.docker_hub_organisation || 'openg2p' }}
          SERVICE_NAME: openg2p-g2p-bridge-celery-beat-producers
          DOCKERFILE_PATH: Dockerfile.producers
          DOCKER_HUB_TOKEN: ${{ secrets.docker_hub_token }}
          DOCKER_HUB_ACTOR: ${{ secrets.docker_hub_actor }}

  docker-build-for-worker:
    name: Docker Build and Push for Celery Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: files
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: jitterbit/get-changed-files@v1
      - name: Check if files changed
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ ${changed_file} =~ ^openg2p-g2p-bridge-models || \
                  ${changed_file} =~ ^openg2p-g2p-bridge-bank-connectors || \
                  ${changed_file} =~ ^openg2p-g2p-bridge-celery-workers || \
                  ${changed_file} == Dockerfile.workers || \
                  ${changed_file} == *.dockerignore ]]
            then
              echo DOCKER_BUILD=true >> $GITHUB_ENV
              break
            fi
          done
      - name: Docker build and push
        uses: ./.github/actions/docker-build
        if: ${{ github.event_name == 'workflow_dispatch' || env.DOCKER_BUILD == 'true' }}
        with:
          NAMESPACE: ${{ secrets.docker_hub_organisation || 'asierneb' }}
          SERVICE_NAME: openg2p-g2p-bridge-celery-workers
          DOCKERFILE_PATH: Dockerfile.workers
          DOCKER_HUB_TOKEN: ${{ secrets.docker_hub_token }}
          DOCKER_HUB_ACTOR: ${{ secrets.docker_hub_actor }}
